### PR TITLE
Plex needs the refresh to be a PUT request

### PR DESCRIPTION
**Pull request by blha303**
Otherwise you get `plexapi.exceptions.BadRequest: (405) method_not_allowed`

### CODE REVIEW

**Comment by mjs7231** [comment]
Thanks.  Must have changed in a recent media server build. :+1:

**Comment by blha303** [comment]
Good thing you pulled it after I actually checked it for bugs and squashed the commits ^_^

**Comment by mjs7231** [comment]
Lol I must have loaded the Files Changed tab right after you removed it.  Because whats in there now is what I saw when I merged it.

**Comment by blha303** [comment]
I had `import requests.put` before, cos that's what I had in my project here and I hadn't tested it to see that it obviously wouldn't work.

**Pull request merged**
