### PR TITLE
Add support for Plex Audio

### PR DESCRIPTION
**Pull request by havardgulldahl**
Initial work to get Plex Audio support. 

This code adds new classes and helper methods, based on the existing video classes, but does not remove existing code.

This lays the path open to refactor and merge the video and audio code paths in the future. 

New classes:

* MusicSection in `library.py` 
* Artist in `audio.py`
* Album in `audio.py`
* Track in `audio.py`

### CODE REVIEW

**Comment by havardgulldahl** [comment]
Here's an example on how to use it:

```python
from plexapi.server import PlexServer
plex = PlexServer("http://192.168.0.105:32400")

from plexapi import audio
from plexapi.library import MusicSection

# list music sections
print(list([s for s in plex.library.sections() if s.TYPE==MusicSection.TYPE]))

# search first music section
music = list([s for s in plex.library.sections() if s.TYPE==MusicSection.TYPE])[0]
roots = music.search('Roots')[0]

# get tracks
tracks = roots.tracks()

# 
t = tracks[0]
print(t.getStreamingUrl()) # for streaming
print([p.key for p in t.iter_parts()]) # get parts directly from server

```

**Comment by tomduijf** [comment]
This looks pretty nice.
I'll give this a testrun somewhere this week!

**Comment by havardgulldahl** [comment]
@tomduijf Great! Let me know how it works for you.

FWIW, I'm currently using it daily in another project, so I'm pretty confident in most of the code paths. Not to say there won't be bugs, of course, so keep me notified about everything you find :)

**Comment by mjs7231** [comment]
This is great!  Thanks again for the code.

**Comment by havardgulldahl** [comment]
Thanks, @mjs7231 !

**Pull request merged**
